name: Landing Page Image Build workflow
on:
  push:
    branches:
      - develop
      - main
      - release/**
    tags:
      - 'v*'
  pull_request:
    branches:
      - develop
      - main
      - release/**
  workflow_dispatch:
  workflow_call:
permissions:
  security-events: write
  contents: read
jobs:
  docker_image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      # Login to Azure Container Registry
      - name: Login to Azure Container Registry
        if: (github.event_name == 'push' && (startsWith(github.ref, 'refs/heads/develop') || startsWith(github.ref, 'refs/heads/release/') || startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/tags/v'))) || github.event_name == 'workflow_dispatch'
        run: docker login -u pucarsolutionsdev -p ${{ secrets.ACR_PASSWORD }} pucarsolutionsdev.azurecr.io
      - name: Set Version from Tag or Branch
        id: set_version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}  # Use tag name for version
          elif [[ "${GITHUB_REF}" == refs/heads/* ]]; then
            # Use branch name as version, replacing '/' with '-'
            VERSION=${GITHUB_REF#refs/heads/}
            VERSION=$(echo "${VERSION}" | sed 's|/|-|g')
          else
            VERSION="latest"  # Default version if not a tag or branch
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Get commit ID
        run: echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV
      - name: Build and Push Docker image for Landing-Page
        if: (github.event_name == 'push' && (startsWith(github.ref, 'refs/heads/develop') || startsWith(github.ref, 'refs/heads/release/') || startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/tags/v'))) || github.event_name == 'workflow_dispatch'
        run: |
          docker build  --build-arg NEXT_PUBLIC_ONCOURTS_API_ENDPOINT=https://dristi-kerala-dev.pucar.org -t pucarsolutionsdev.azurecr.io/oncourts-landing-page:${{ env.VERSION }}-${{ env.COMMIT_ID }} .
          docker push pucarsolutionsdev.azurecr.io/oncourts-landing-page:${{ env.VERSION }}-${{ env.COMMIT_ID }}
